#
# Copyright (C) 2020 diva.exchange
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Author/Maintainer: Konrad Bächler <konrad@diva.exchange>
#

version: "3.7"
services:
  i2p.testnet.diva.i2p:
    container_name: i2p.testnet.diva.i2p
    image: divax/i2p:latest
    restart: unless-stopped
    environment:
      ENABLE_TUNNELS: 1
    volumes:
      - ../tunnels.conf.d/join:/home/i2pd/tunnels.source.conf.d/
      - i2p.testnet.diva.i2p:/home/i2pd/data/
    networks:
      network.testnet.diva.i2p:
        ipv4_address: 172.20.101.200

  nx.db.testnet.diva.i2p:
    container_name: nx.db.testnet.diva.i2p
    image: postgres:10-alpine
    command: -c max_prepared_transactions=100
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: iroha
      POSTGRES_USER: iroha
      POSTGRES_PASSWORD: iroha
    volumes:
      - nx.db.testnet.diva.i2p:/var/lib/postgresql/data/
    networks:
      network.testnet.diva.i2p:
        ipv4_address: 172.20.101.2

  node.testnet.diva.i2p:
    container_name: node.testnet.diva.i2p
    image: divax/diva-api:latest
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      IP_LISTEN: 172.20.101.201
      PORT_LISTEN: 19012
      TORII: 172.20.101.3:50051
      I2P_HOSTNAME: 172.20.101.200
      I2P_HTTP_PROXY_PORT: 4444
      I2P_WEBCONSOLE_PORT: 7070
      BOOTSTRAP_PEER: ${BOOTSTRAP_PEER:-}
      PATH_IROHA: ${PATH_IROHA:-/tmp/iroha/}
    volumes:
      - nx.testnet.diva.i2p:/tmp/iroha/
      - node.testnet.diva.i2p:/home/node/data/
    networks:
      network.testnet.diva.i2p:
        ipv4_address: 172.20.101.201

  nx.testnet.diva.i2p:
    container_name: nx.testnet.diva.i2p
    image: divax/iroha:latest
    restart: unless-stopped
    stop_grace_period: 30s
    environment:
      IP_POSTGRES: 172.20.101.2
      NAME_DATABASE: iroha
      BLOCKCHAIN_NETWORK: testnet.diva.i2p
      IP_HTTP_PROXY: 172.20.101.200
      PORT_HTTP_PROXY: 4444
    volumes:
      - nx.testnet.diva.i2p:/opt/iroha/
    networks:
      network.testnet.diva.i2p:
        ipv4_address: 172.20.101.3

  explorer.testnet.diva.i2p:
    container_name: explorer.testnet.diva.i2p
    image: divax/iroha-explorer:latest
    restart: unless-stopped
    environment:
      IP_EXPLORER: 0.0.0.0
      PORT_EXPLORER: 3920
      PATH_IROHA: /tmp/iroha/
    volumes:
      - nx.testnet.diva.i2p:/tmp/iroha/:ro
    networks:
      network.testnet.diva.i2p:
        ipv4_address: 172.20.101.100

networks:
  network.testnet.diva.i2p:
    name: network.testnet.diva.i2p
    ipam:
      driver: default
      config:
        - subnet: 172.20.101.0/24

volumes:
  i2p.testnet.diva.i2p:
    name: i2p.testnet.diva.i2p
  nx.db.testnet.diva.i2p:
    name: nx.db.testnet.diva.i2p
  node.testnet.diva.i2p:
    name: node.testnet.diva.i2p
  nx.testnet.diva.i2p:
    name: nx.testnet.diva.i2p
