#
# Copyright (C) 2020 diva.exchange
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Author/Maintainer: Konrad Bächler <konrad@diva.exchange>
#

version: "3.7"
services:
  n1.db.testnet.diva.local:
    container_name: n1.db.testnet.diva.local
    image: postgres:10-alpine
    command: -c max_prepared_transactions=100
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: iroha
      POSTGRES_USER: iroha
      POSTGRES_PASSWORD: iroha
    volumes:
      - n1.db.testnet.diva.local:/var/lib/postgresql/data/
    networks:
      network.testnet.diva.local:
        ipv4_address: 172.29.101.11

  n1.testnet.diva.local:
    container_name: n1.testnet.diva.local
    image: divax/iroha:latest
    restart: unless-stopped
    environment:
      IP_POSTGRES: 172.29.101.11
      NAME_PEER: n1
      BLOCKCHAIN_NETWORK: testnet.diva.local
    volumes:
      - n1.testnet.diva.local:/opt/iroha/
    networks:
      network.testnet.diva.local:
        ipv4_address: 172.29.101.12
    extra_hosts:
      - n1.testnet.diva.local:172.29.101.12

networks:
  network.testnet.diva.local:
    internal: true
    name: network.testnet.diva.local
    ipam:
      driver: default
      config:
        - subnet: 172.29.101.0/24

volumes:
  n1.testnet.diva.local:
    name: n1.testnet.diva.local
  n1.db.testnet.diva.local:
    name: n1.db.testnet.diva.local
